import wixData from "wix-data";
import wixLocation from "wix-location";
import { currentMember } from "wix-members-frontend";

/**
 * Herald Primary Feed (List Page)
 *
 * Renders a dynamic, article-led feed of individual article cards using a
 * Wix Repeater bound to the CPA_Herald_Articles collection. Supports:
 *
 *  - Card composition: cover_image, title, author_name, category tags
 *  - Premium badge overlay for gated articles (is_premium === true)
 *  - Interactive hashtag filtering via Selection Tags (no page reload)
 *  - Free-text search against title and author_name
 *  - Click-through navigation to the dynamic item page
 *
 * Wix Editor Prerequisites:
 *  - A Dataset element (#dynamicDataset) bound to CPA_Herald_Articles,
 *    sorted by published_date descending.
 *  - A Repeater element (#articleRepeater) with the following child elements
 *    inside each repeated item:
 *      #coverImage   — Image element for the article thumbnail
 *      #articleTitle  — Text element for the article title
 *      #authorName    — Text element for the author name
 *      #categoryLabel — Text element for displaying category tags
 *      #premiumBadge  — Container/Box element (lock icon or "Subscriber
 *                       Exclusive" label), initially collapsed in the Editor
 *      #cardContainer — The outermost Box/Container for click handling
 *  - A Selection Tags element (#categoryTags) above the repeater.
 *  - A Text Input element (#searchInput) and Button (#searchButton).
 *  - A Text element (#noResultsText), initially collapsed.
 */

$w.onReady(function () {
  // ─── Dataset Ready ──────────────────────────────────────────────
  $w("#dynamicDataset").onReady(() => {
    console.log("Herald List Page: Dataset ready.");

    // Bind the repeater item rendering
    _setupRepeater();

    // Bind the tag filtering
    _setupCategoryFiltering();

    // Bind the search
    _setupSearch();
  });
});

// ═══════════════════════════════════════════════════════════════════
// REPEATER SETUP
// ═══════════════════════════════════════════════════════════════════

/**
 * Configures the repeater's onItemReady callback to populate each card.
 */
function _setupRepeater() {
  $w("#articleRepeater").onItemReady(($item, itemData, index) => {
    // Cover image
    if (itemData.cover_image) {
      $item("#coverImage").src = itemData.cover_image;
    }

    // Title
    $item("#articleTitle").text = itemData.title || "";

    // Author name
    $item("#authorName").text = itemData.author_name || "";

    // Category tags — join array into a readable label
    if (itemData.category_tags && itemData.category_tags.length > 0) {
      $item("#categoryLabel").text = itemData.category_tags.join("  ·  ");
    } else {
      $item("#categoryLabel").text = "";
    }

    // Premium badge overlay — show only for premium articles
    if (itemData.is_premium) {
      $item("#premiumBadge").expand();
    } else {
      $item("#premiumBadge").collapse();
    }

    // Click handler — navigate to dynamic item page
    $item("#cardContainer").onClick(() => {
      // Use the dynamic page link field generated by Wix
      const dynamicUrl = itemData["link-CPA_Herald_Articles-title"];
      if (dynamicUrl) {
        wixLocation.to(dynamicUrl);
      }
    });
  });
}

// ═══════════════════════════════════════════════════════════════════
// CATEGORY TAG FILTERING
// ═══════════════════════════════════════════════════════════════════

/**
 * Listens for changes on the Selection Tags element and dynamically
 * filters the dataset without triggering a page reload.
 */
function _setupCategoryFiltering() {
  $w("#categoryTags").onChange((event) => {
    const selectedTags = event.target.value; // Array of selected tag labels

    _applyFilters(selectedTags, _getCurrentSearchQuery());
  });
}

// ═══════════════════════════════════════════════════════════════════
// FREE-TEXT SEARCH
// ═══════════════════════════════════════════════════════════════════

/**
 * Binds the search button click and Enter key to filter the dataset
 * by title or author_name using .contains().
 */
function _setupSearch() {
  // Search on button click
  $w("#searchButton").onClick(() => {
    _executeSearch();
  });

  // Search on Enter key
  $w("#searchInput").onKeyPress((event) => {
    if (event.key === "Enter") {
      _executeSearch();
    }
  });
}

/**
 * Reads the current search query and applies combined filters.
 */
function _executeSearch() {
  const query = _getCurrentSearchQuery();
  const selectedTags = $w("#categoryTags").value || [];

  _applyFilters(selectedTags, query);
}

/**
 * Returns the trimmed search query from the input.
 * @returns {string}
 */
function _getCurrentSearchQuery() {
  return ($w("#searchInput").value || "").trim();
}

// ═══════════════════════════════════════════════════════════════════
// COMBINED FILTER APPLICATION
// ═══════════════════════════════════════════════════════════════════

/**
 * Applies both tag and search filters to the dataset simultaneously.
 * This ensures tags and search work together rather than overriding each other.
 *
 * @param {Array<string>} selectedTags - Currently selected category tags.
 * @param {string} searchQuery - Current free-text search string.
 */
function _applyFilters(selectedTags, searchQuery) {
  let filter = wixData.filter();

  // Apply tag filter if any tags are selected
  if (selectedTags && selectedTags.length > 0) {
    filter = filter.hasSome("category_tags", selectedTags);
  }

  // Apply search filter if a search query is present
  if (searchQuery && searchQuery.length > 0) {
    filter = filter.and(
      wixData
        .filter()
        .contains("title", searchQuery)
        .or(wixData.filter().contains("author_name", searchQuery))
    );
  }

  // Set the filter on the dataset — no page reload
  $w("#dynamicDataset")
    .setFilter(filter)
    .then(() => {
      // Show/hide "no results" message
      const count = $w("#dynamicDataset").getTotalCount();
      if (count === 0) {
        $w("#noResultsText").expand();
      } else {
        $w("#noResultsText").collapse();
      }
      console.log(`Herald List Page: Filter applied. ${count} results.`);
    })
    .catch((err) => {
      console.error("Herald List Page: Filter failed:", err);
    });
}
