import wixData from "wix-data";
import wixLocation from "wix-location";
import { currentMember } from "wix-members-frontend";

/**
 * Herald Primary Feed (List Page)
 *
 * Renders a dynamic, article-led feed of individual article cards using a
 * Wix Repeater bound to the HeraldArticles collection. Supports:
 *
 *  - Card composition: coverImage, title, authorName, category tags
 *  - Premium badge overlay for gated articles (premiumPlan === true)
 *  - Interactive hashtag filtering via Selection Tags (no page reload)
 *  - Free-text search against title and authorName
 *  - Click-through navigation to the dynamic item page
 *
 * Wix Editor Prerequisites:
 *  - A Dataset element (#dynamicDataset) bound to HeraldArticles,
 *    sorted by published_date descending.
 *  - A Repeater element (#articleRepeater) with the following child elements
 *    inside each repeated item:
 *      #coverImage   — Image element for the article thumbnail
 *      #articleTitle  — Text element for the article title
 *      #authorName    — Text element for the author name
 *      #categoryLabel — Text element for displaying category tags
 *      #premiumBadge  — Container/Box element (lock icon or "Subscriber
 *                       Exclusive" label), initially collapsed in the Editor
 *      #cardContainer — The outermost Box/Container for click handling
 *  - A Selection Tags element (#categoryTags) above the repeater.
 *  - A Text Input element (#searchInput) and Button (#searchButton).
 *  - A Text element (#noResultsText), initially collapsed.
 */

$w.onReady(function () {
  console.log("Herald List Page: page $w.onReady triggered.");
  
  // Bind the repeater item rendering immediately before the dataset loads data
  console.log("Herald List Page: calling _setupRepeater()");
  _setupRepeater();

  // Bind the tag filtering
  console.log("Herald List Page: calling _setupCategoryFiltering()");
  _setupCategoryFiltering();

  $w("#dynamicDataset").onReady(() => {
    console.log("Herald List Page: Dataset onReady event fired.");
    _refreshRepeater();
  });
});

// ═══════════════════════════════════════════════════════════════════
// REPEATER SETUP
// ═══════════════════════════════════════════════════════════════════

/**
 * Configures the repeater's onItemReady callback to populate each card.
 */
function _setupRepeater() {
  console.log("Herald List Page: Registering onItemReady on #articleRepeater");
  $w("#articleRepeater").onItemReady(($item, itemData, index) => {
    console.log(`Herald List Page: onItemReady triggered for index ${index}. itemData:`, itemData);
    
    // Cover image (database uses coverImage)
    if (itemData.coverImage) {
      console.log(`Herald List Page: setting coverImage for index ${index} to ${itemData.coverImage}`);
      $item("#coverImage").src = itemData.coverImage;
    } else {
      console.log(`Herald List Page: no coverImage for index ${index}`);
    }

    // Title
    console.log(`Herald List Page: setting title for index ${index} to ${itemData.title}`);
    $item("#articleTitle").text = itemData.title || "";

    // Author name (database uses authorName)
    console.log(`Herald List Page: setting authorName for index ${index} to ${itemData.authorName}`);
    $item("#authorName").text = itemData.authorName || "";

    // Category tags — populate selection tags options and values
    if (itemData.category_tags && itemData.category_tags.length > 0) {
      console.log(`Herald List Page: setting categoryLabel options/values for index ${index} to`, itemData.category_tags);
      $item("#categoryLabel").options = itemData.category_tags.map(tag => ({ label: tag, value: tag }));
      $item("#categoryLabel").value = itemData.category_tags;
    } else {
      console.log(`Herald List Page: empty categoryLabel for index ${index}`);
      $item("#categoryLabel").options = [];
      $item("#categoryLabel").value = [];
    }

    // Premium badge overlay — show only for premium articles (database uses premiumPlan)
    if (itemData.premiumPlan) {
      console.log(`Herald List Page: expanding premiumBadge for index ${index}`);
      $item("#premiumBadge").expand();
    } else {
      console.log(`Herald List Page: collapsing premiumBadge for index ${index}`);
      $item("#premiumBadge").collapse();
    }

    // Click handler — navigate to dynamic item page
    $item("#cardContainer").onClick(() => {
      // Use the dynamic page link field generated by Wix for HeraldArticles
      const dynamicUrl = itemData["link-herald-articles-title"];
      console.log(`Herald List Page: Clicked index ${index}. Navigating to:`, dynamicUrl);
      if (dynamicUrl) {
        wixLocation.to(dynamicUrl);
      }
    });
  });
}

/**
 * Manually fetches items from the dataset and populates the repeater.
 */
function _refreshRepeater() {
  console.log("Herald List Page: Refreshing repeater data from dataset...");
  $w("#dynamicDataset").getItems(0, 100)
    .then((result) => {
      console.log("Herald List Page: Retrieved items count =", result.items.length);
      $w("#articleRepeater").data = result.items;
    })
    .catch((err) => {
      console.error("Herald List Page: Failed to refresh repeater items:", err);
    });
}

// ═══════════════════════════════════════════════════════════════════
// CATEGORY TAG FILTERING
// ═══════════════════════════════════════════════════════════════════

/**
 * Listens for changes on the Selection Tags element and dynamically
 * filters the dataset without triggering a page reload.
 */
function _setupCategoryFiltering() {
  $w("#categoryTags").onChange((event) => {
    const selectedTags = event.target.value; // Array of selected tag labels
    console.log("Herald List Page: tag selection changed:", selectedTags);
    _applyFilters(selectedTags);
  });
}

// ═══════════════════════════════════════════════════════════════════
// COMBINED FILTER APPLICATION
// ═══════════════════════════════════════════════════════════════════

/**
 * Applies tag filters to the dataset.
 *
 * @param {Array<string>} selectedTags - Currently selected category tags.
 */
function _applyFilters(selectedTags) {
  console.log("Herald List Page: applying filters for tags:", selectedTags);
  let filter = wixData.filter();

  // Apply tag filter if any tags are selected
  if (selectedTags && selectedTags.length > 0) {
    filter = filter.hasSome("category_tags", selectedTags);
  }

  // Set the filter on the dataset — no page reload
  $w("#dynamicDataset")
    .setFilter(filter)
    .then(() => {
      const count = $w("#dynamicDataset").getTotalCount();
      console.log(`Herald List Page: Filter applied. ${count} results.`);
      _refreshRepeater();
    })
    .catch((err) => {
      console.error("Herald List Page: Filter failed:", err);
    });
}
